# Generated by Django 2.1.7 on 2019-04-15 22:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20190327_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='question',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Payment',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True),
        ),
    ]
