# Generated by Django 2.1.7 on 2019-02-21 20:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('Cuisine_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Cusine_Sub', models.CharField(max_length=20)),
                ('Cusine_parent', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('Menu_Item_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Menu_Item', models.CharField(max_length=50)),
                ('Menu_ItemPrice', models.IntegerField()),
                ('Menu_Item_Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('Res_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Res_Name', models.CharField(max_length=75)),
                ('Res_Description', models.CharField(max_length=150, null=True)),
                ('Res_Contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('Res_Address', models.CharField(max_length=75)),
                ('Cuisine_Type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('Review_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Review_Des', models.CharField(blank=True, max_length=75)),
                ('Res_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='Menu_Res_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='Menu_Item_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Menu'),
        ),
    ]
