# Generated by Django 2.1.7 on 2019-03-21 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20190320_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Menu_Res_Id',
            field=models.ForeignKey(blank='false', null='false', on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
