# Generated by Django 2.1.7 on 2019-03-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20190320_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Menu_ItemPrice',
            field=models.FloatField(),
        ),
    ]
