# Generated by Django 2.1.7 on 2019-03-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20190320_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Menu_ItemPrice',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
