# Generated by Django 2.1.7 on 2019-03-27 06:03

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20190320_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Res_Pic',
            field=models.ImageField(default='/img/defaultimage.png', upload_to=restaurant.models.Restaurant.upload_image),
        ),
    ]
