# Generated by Django 2.1.7 on 2019-03-28 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20190327_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Review_Rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
