# Generated by Django 2.1.7 on 2019-03-29 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_review_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='Cusine_Sub',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='Menu_Item_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Menu'),
        ),
    ]
