# Generated by Django 2.1.7 on 2019-03-28 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_review_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='Menu_Item_Id',
        ),
        migrations.AddField(
            model_name='menu',
            name='Menu_Cusine',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.Cuisine'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='Cusine_Sub',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Menu_Res_Id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
            preserve_default=False,
        ),
    ]
