# Generated by Django 2.1.7 on 2019-03-30 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20190328_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='Cusine_parent',
            field=models.CharField(default='International', max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Menu_Cusine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Cuisine'),
        ),
    ]
