# Generated by Django 2.1.7 on 2019-03-30 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20190330_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Menu_Cusine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Cuisine'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Cuisine_Type',
            field=models.CharField(max_length=25),
        ),
    ]
