# Generated by Django 2.1.7 on 2019-03-30 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_remove_menu_menu_cusine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='Label_Menu_Id',
        ),
        migrations.AddField(
            model_name='menu',
            name='Menu_Cusine',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Cuisine'),
        ),
        migrations.AddField(
            model_name='menu',
            name='Menu_Label_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Label'),
        ),
    ]
