# Generated by Django 2.1.7 on 2019-03-30 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_remove_menu_menu_cusine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='Menu_Label_Id',
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='Cusine_parent',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Menu_Res_Id',
            field=models.ForeignKey(blank='false', null='false', on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Cuisine_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Cuisine'),
        ),
    ]
