# Generated by Django 2.1.7 on 2019-03-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_menu_menu_cuisine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuisine',
            old_name='Cusine_Sub',
            new_name='Cuisine_Sub',
        ),
        migrations.RenameField(
            model_name='cuisine',
            old_name='Cusine_parent',
            new_name='Cuisine_parent',
        ),
    ]
