# Generated by Django 2.1.7 on 2019-03-31 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0031_menu_menu_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Menu_Cuisine',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Cuisine'),
        ),
    ]
