# Generated by Django 2.1.7 on 2019-03-31 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0033_auto_20190331_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Menu_Res_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
