# Generated by Django 2.1.7 on 2019-03-31 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0034_auto_20190331_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='Menu_Cuisine',
        ),
    ]
