# Generated by Django 2.1.7 on 2019-03-31 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0038_auto_20190331_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('Menu_Item_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Menu_Item', models.CharField(max_length=50)),
                ('Menu_ItemPrice', models.DecimalField(decimal_places=2, max_digits=30)),
                ('Menu_Item_Description', models.CharField(max_length=100)),
                ('Menu_Cuisine', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Cuisine')),
                ('Menu_Label_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Label')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Cuisine_Type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Cuisine'),
        ),
        migrations.AddField(
            model_name='menu',
            name='Menu_Res_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
