# Generated by Django 2.1.7 on 2019-03-31 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0039_auto_20190331_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Menu_Label_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Label'),
        ),
    ]
