# Generated by Django 2.1.7 on 2019-03-31 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0040_auto_20190331_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='Cuisine_Pic',
            field=models.ImageField(default='/media/defaultimage.png', upload_to=restaurant.models.Cuisine.upload_image),
        ),
        migrations.AddField(
            model_name='menu',
            name='Menu_Pic',
            field=models.ImageField(default='/media/defaultimage.png', upload_to=restaurant.models.Menu.upload_image),
        ),
        migrations.AddField(
            model_name='review',
            name='Review_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
