# Generated by Django 2.1.7 on 2019-03-31 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0041_auto_20190331_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Menu_Label_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Label'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Cuisine_Type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Cuisine'),
        ),
    ]
