# Generated by Django 2.1.7 on 2019-04-01 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0042_auto_20190331_1733'),
        ('restaurant', '0010_auto_20190329_1727'),
    ]

    operations = [
    ]
