# Generated by Django 2.1.7 on 2019-04-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0042_auto_20190331_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='Cuisine_Pic',
            field=models.ImageField(default='/media/defaultimage.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Menu_Pic',
            field=models.ImageField(default='/media/defaultimage.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Res_Pic',
            field=models.ImageField(default='/media/defaultimage.png', upload_to='media/'),
        ),
    ]
