# Generated by Django 2.1.7 on 2019-04-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0043_merge_20190401_1838'),
        ('restaurant', '0043_auto_20190401_2252'),
    ]

    operations = [
    ]
