# Generated by Django 2.1.7 on 2019-04-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0044_merge_20190402_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Menu_Pic',
            field=models.ImageField(default='defaultimage.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Res_Pic',
            field=models.ImageField(default='defaultimage.png', upload_to='media/'),
        ),
    ]
