# Generated by Django 2.1.7 on 2019-03-29 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0010_auto_20190329_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Menu_Item', models.CharField(max_length=300)),
                ('Order_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Preferences', models.CharField(max_length=300)),
                ('Restaurant_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
    ]
