# Generated by Django 2.1.7 on 2019-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190421_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
