# Generated by Django 2.1.7 on 2019-04-26 17:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Deliverer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Deliverer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='Payment',
            field=models.IntegerField(default=None,null=True ,validators=[django.core.validators.MaxValueValidator(999999999999999)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
