# Generated by Django 2.1.7 on 2019-04-26 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190426_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Payment',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999999999)]),
        ),
    ]
