# Generated by Django 2.1.7 on 2019-04-29 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190426_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 1, 10, 2, 702475)),
        ),
    ]
