# Generated by Django 2.1.7 on 2019-04-29 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orders_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Status',
            field=models.CharField(choices=[('s', 'submitted'), ('r', 'Restaurant'), ('d', 'Delivery'), ('e', 'Declined')], default='s', max_length=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 10, 8, 33, 294222)),
        ),
    ]
